version: '3'


services:
    utm_egais_monitor_grafana:
        image: grafana/grafana:latest
        container_name: utm_egais_monitor_grafana
        volumes:
            - ./utm_egais_monitor/data/grafana/data:/var/lib/grafana
          #- ./utm_egais_monitor/data/grafana/config.ini:/etc/grafana/grafana.ini
          #- ./utm_egais_monitor/data/grafana/log:/var/log/
        ports:
            - 36020:3000
        links:
            - utm_egais_monitor_prometheus:prometheus
        environment:
            - GF_SECURITY_ADMIN_USER=admin
            - GF_SECURITY_ADMIN_PASSWORD=changeme
            - GF_USERS_ALLOW_SIGN_UP=false
            - GF_SERVER_DOMAIN=myrul.com
          # - GF_SMTP_ENABLED=true
          # - GF_SMTP_HOST=smtp.gmail.com:587
          # - GF_SMTP_USER=@gmail.com
          # - GF_SMTP_PASSWORD=mypassword
          # - GF_SMTP_FROM_ADDRESS=myaddress@gmail.com
        user: "0"
        # environment:
            # - VIRTUAL_HOST=tests.tk
            # - LETSENCRYPT_HOST=tests.tk
        # restart: unless-stopped

    utm_egais_monitor_prometheus:
        image: prom/prometheus:latest
        container_name: utm_egais_monitor_prometheus
        volumes:
            - ./utm_egais_monitor/data/prometheus/config:/etc/prometheus/
            - ./utm_egais_monitor/data/prometheus/data:/prometheus
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus'
        # expose:
            # - 9090
        ports:
            - 36021:9090
        user: "0"
        # restart: unless-stopped